[module]
[module.hugoVersion]

theme = "poison"
baseURL = "https://mrlrnt.github.io/"
languageCode = "fr"
paginate = 10
pluralizelisttitles = false   # removes the automatically appended "s" on sidebar entries.

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    brand = "mrlrnt"                      # name of your site - appears in the sidebar
    brand_image = "/avatar.jpg"     
    #description = "OSINT Stuff"
    dark_mode = false                     # optional - defaults to false

    # MENU PLACEHOLDER
    # menu dict keys:
        # name:         Nom
        # URL:          The directory relative to the content directory.
        # HasChildren:  If the directory's files should be listed.  Default is true.
        # Limit:        If the files should be listed, how many should be shown.
 
   menu = [
        {Name = "About", URL = "/about/", HasChildren = false, Limite = 1},
        {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
    ]
  
    # Links to your socials.  Delete any you don't need/use. 
    twitter_url = "https://twitter.com/mrlrnt"
    tryhackme_url = "https://tryhackme.com/p/laurentlt"
    #github_url = ""
    ozint_url = "https://ozint.eu/ozinter/2354/"
    #linkedin_url = ""
    #gitlab_url = "https://gitlab.com"
    #mastodon_url = "https://mastodon.social"
    #discord_url = "https://discord.com"
    #youtube_url = "https://youtube.com"
    #instagram_url = "https://instagram.com"
    #facebook_url = "https://facebook.com"
    protonmail_url = "mailto:mrlrnt@protonmail.com"
    #rootme_url = "https://www.root-me.org/mrlrnt"
   

    # Hex colors for your sidebar.
    sidebar_bg_color = "#202020"            # default is #202020
    sidebar_img_border_color = "#515151"    # default is #515151
    sidebar_p_color = "#909090"             # default is #909090
    sidebar_h1_color = "#FFF"               # default is #FFF
    sidebar_a_color = "#FFF"                # default is #FFF
    sidebar_socials_color = "#FFF"          # default is #FFF
    moon_sun_color = "#FFF"                 # default is #FFF
    moon_sun_background_color = "#515151"   # default is #515151

    # Hex colors for your content in light mode.
    text_color = "#222"             # default is #222
    content_bg_color = "#FAF9F6"    # default is #FAF9F6
    post_title_color = "#303030"    # default is #303030
    list_color = "#5a5a5a"          # default is #5a5a5a
    link_color = "#268bd2"          # default is #268bd2
    date_color = "#515151"          # default is #515151

    # Hex colors for your content in dark mode
    text_color_dark = "#eee"            # default is #eee
    content_bg_color_dark = "#121212"   # default is #121212
    post_title_color_dark = "#DBE2E9"   # default is #DBE2E9
    list_color_dark = "#9d9d9d"         # default is #9d9d9d
    link_color_dark = "#268bd2"         # default is #268bd2
    date_color_dark = "#9a9a9a"         # default is #9a9a9a

[taxonomies]
    series = 'series'
    tags = 'tags'
